### ISSUE TITLE
📲 Form-ul se micsoreaza prea mult pe rezolutii mai mici

### ISSUE THREAD

**Issue by richardbaltariu** [GabrielaManea/react-app#4]
In loc de `width: 30vw` eu as alege: 
```css
.register-container {
    max-width: 320px; 
    width: 100%;
}
```

![image](https://user-images.githubusercontent.com/39081704/78877526-a8269400-7a59-11ea-8fb6-f9a0a397d6c0.png)
